### ISSUE TITLE
Fix or prevent problems on site with HTML, CSS, JS

### ISSUE THREAD

**Issue by khusnetdinov** [howtohireme/ruby.fundamental#75]
Need to remove problems that were found on SEO checkers sites:
[validator.w3.org](https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&checkerrorpages=yes&useragent=Validator.nu%2FLV+http%3A%2F%2Fvalidator.w3.org%2Fservices&acceptlanguage=&doc=https%3A%2F%2Fbetterdocs.herokuapp.com%2F)
[seo-audit](https://seositecheckup.com/seo-audit/betterdocs.herokuapp.com)
[seowebpageanalyzer.](http://www.seowebpageanalyzer.com/)

**Comment by aisayo** [comment]
Hi, 

for the first error 

`Error: A meta element with an http-equiv attribute whose value is X-UA-Compatible must have a content attribute with the value IE=edge.

From line 7, column 1; to line 7, column 63

"utf-8"/>↩<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>↩<meta`


it looks like removing the `chrome=1` fixes the validation per this discussion https://stackoverflow.com/questions/28108614/why-does-http-equiv-x-ua-compatible-content-ie-edge-chrome-1-is-not-validate

**Comment by OleksSobol** [comment]
I can try it!

**Comment by OleksSobol** [comment]
#75 Hi! I think I did everything in my knowledge! You might want check it!
