### ISSUE TITLE
first error

### ISSUE THREAD

**Issue by aisayo** [howtohireme/ruby.fundamental#91]
Hi,

for the first error

`Error: A meta element with an http-equiv attribute whose value is X-UA-Compatible must have a content attribute with the value IE=edge.

From line 7, column 1; to line 7, column 63

"utf-8"/>↩↩<meta`

it looks like removing the chrome=1 fixes the validation per this discussion https://stackoverflow.com/questions/28108614/why-does-http-equiv-x-ua-compatible-content-ie-edge-chrome-1-is-not-validate

**Comment by khusnetdinov** [comment]
@aisayo, Thanks for the issue. This problem relates to another [issue](https://github.com/howtohireme/ruby.fundamental/issues/75) that have been started by another developer.

**Comment by OleksSobol** [comment]
I fixed that. Thank you!
